steps:
#step 1
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/$PROJECT_ID/gateway:$BRANCH_NAME-$COMMIT_SHA',
   '-t', 
   'gcr.io/$PROJECT_ID/gateway:latest',
   '.'
  ]
#step 2
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
#step 2
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'gateway', 
   'gateway=gcr.io/$PROJECT_ID/gateway:$BRANCH_NAME-$COMMIT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
# push images to Google Container Registry with tags
images: [
   'gcr.io/$PROJECT_ID/gateway:$BRANCH_NAME-$COMMIT_SHA',
   'gcr.io/$PROJECT_ID/gateway:latest'
  ]