apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - image: gcr.io/fdx-3d-build-253407/gateway:latest
        name: gateway
        env:
        - name: ECOMM_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: env-var
              key: ECOMM_SERVICE_URL
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: env-var
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: env-var
              key: DB_NAME 
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: env-var
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              name: env-var
              key: DB_PASS
        ports:
        - containerPort: 8081
      nodeSelector:
        cloud.google.com/gke-nodepool : micro-service-node